apiVersion: v1
kind: Service
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: glpi
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - image: hatoua20s/glpipfe:v1
        name: glpi
        env:
       - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_HOST
          value: "mysql-glpi"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "testing"
        - name: MYSQL_USER
          value: "glpi"
        - name: MYSQL_PASSWORD
          value: "glpi"		
        ports:
        - containerPort: 80
          name: glpi
