apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: glpi
  name: mysql-ext
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31016
  selector:
    app: mysqli
  type: NodePort
status:
  loadBalancer: {}
